apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
{{- include "python-hello.labels" . | indent 4 }}
{{- include "python-hello.commonLabels" . | indent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  annotations:
{{- include "python-hello.annotations" . | indent 4 }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
data:
  readme: |-
{{ .Values.config.readme | indent 4 }}
