apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.name }}.localdomain
    http:
      paths:
      - path: 
        backend:
          serviceName: {{ .Values.name }}
          servicePort: 8080
