{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-{{ .Values.name }}
  labels:
{{- include "python-hello.labels" . | indent 4 }}
{{- include "python-hello.commonLabels" . | indent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  annotations:
{{- include "python-hello.annotations" . | indent 4 }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Values.name }}
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.name }}
  labels:
{{- include "python-hello.labels" . | indent 4 }}
{{- include "python-hello.commonLabels" . | indent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{- include "python-hello.annotations" . | indent 4 }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.name }}.localdomain
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: 8080
{{- end }}
