apiVersion: v2
name: java-hello-world
description: A Helm chart to deploy a Java hello-world application using Spring Boot.
type: application
version: 0.1.0
appVersion: 1.0.0
home: https://github.com/shellclear/helm/java-hello-world
sources:
  - https://github.com/shellclear/helm/java-hello-world
icon: https://spring.io/images/spring-initializr-4291cc0115eb104348717b82161a81de.svg
keywords:
  - springboot
  - java
  - java-hello-world
maintainers:
  - name: Paulo Pacifico
    email: shellclear@gmail.com
