apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "hello-world-sb.labels" . | nindent 4 }}
    {{- include "hello-world-sb.commonLabels" . | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.name }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app_name: {{ .Values.name }}
    deploymentconfig: {{ .Values.name }}
