apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
{{- include "sb-hello-world.labels" . | indent 4 }}
{{- include "sb-hello-world.commonLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    app_name: {{ .Values.name }}
  template:
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.version }}
