apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
{{- include "sb-hello-world.labels" . | indent 4 }}
{{- include "sb-hello-world.commonLabels" . | indent 4 }}
spec:
  ports:
  - name: {{ .Values.name }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app_name: {{ .Values.name }}
<<<<<<< HEAD:sb-hello-world/templates/service.yaml
 
=======
 
>>>>>>> 5eb4f865607cc4fb9226a1dba731101519197dcd:charts/hello-world-sb/templates/service.yaml
